"""Field contracts recovered from the Pentaho Sucursales transformations."""

from __future__ import annotations

ATENCIONES_SOURCE_FIELDS = (
    "ID_Ticket",
    "ID_Llamada",
    "ID_Oficina",
    "Codigo_de_Oficina",
    "Oficina",
    "ID_Serie",
    "Serie",
    "ID_Linea",
    "Fila",
    "Modulo",
    "DNI_Ejecutivo",
    "Nombre_Ejecutivo",
    "Fecha",
    "Prefijo_Ticket",
    "Nro._Ticket",
    "DNI_Cliente",
    "ID_Tipo_Cliente",
    "Tipo_Cliente",
    "Nombre_Cliente",
    "Email_Cliente",
    "Hora_Emision_Ticket",
    "Hora_Inicio_Atencion",
    "Hora_Termino_Atencion",
    "Tiempo_Espera",
    "Tiempo_Atencion",
    "ID_Motivos",
    "Motivo_Atencion",
    "Perdido",
    "Saltado",
    "Formulario",
    "Modo_de_Atencion",
)

ATENCIONES_BASE_FIELDS = (
    "fechaCierre",
    "ID_Ticket",
    "ID_Llamada",
    "ID_Oficina",
    "Codigo_de_Oficina",
    "Oficina",
    "ID_Serie",
    "Serie",
    "ID_Linea",
    "Fila",
    "Modulo",
    "DNI_Ejecutivo",
    "Nombre_Ejecutivo",
    "Fecha",
    "Prefijo_Ticket",
    "Nro._Ticket",
    "DNI_Cliente",
    "ID_Tipo_Cliente",
    "Tipo_Cliente",
    "Nombre_Cliente",
    "Email_Cliente",
    "Hora_Emision_Ticket",
    "Hora_Inicio_Atencion",
    "Hora_Termino_Atencion",
    "Tiempo_Espera",
    "Tiempo_Atencion",
    "Perdido",
    "Saltado",
    "Formulario",
    "Modo_de_Atencion",
)

AGENDAMIENTOS_SOURCE_FIELDS = (
    "ID_Reserva",
    "ID_Llamada",
    "ID_Oficina",
    "Codigo_de_Oficina",
    "Oficina",
    "ID_Serie",
    "Serie",
    "ID_Linea",
    "Fila",
    "Modulo",
    "DNI_Ejecutivo",
    "Nombre_Ejecutivo",
    "Fecha_Reserva",
    "Hora_Reserva",
    "Prefijo_Fila",
    "Terminal_Reserva",
    "DNI_Cliente",
    "ID_Tipo_Cliente",
    "Tipo_Cliente",
    "Nombre_Cliente",
    "Email_Cliente",
    "Fecha_Creacion_Reserva",
    "Hora_Creacion_Reserva",
    "Fecha_Atencion",
    "Hora_Atencion",
    "Hora_Termino_Atencion",
    "Tiempo_Espera",
    "Tiempo_Atencion",
    "Cancelado",
    "Fecha_Cancelacion",
    "Usuario_que_Cancelo",
    "Motivo_de_Cancelacion",
    "ID_Motivos",
    "Motivo_Atencion",
    "Formulario",
    "Perdido",
    "Saltado",
    "Origen_de_Creacion",
    "Nombre_Agente",
    "Email_Agente",
    "DNI_Agente",
    "Modo_de_Atencion",
)

AGENDAMIENTOS_BASE_FIELDS = (
    "fechaCierre",
    "ID_Reserva",
    "ID_Llamada",
    "ID_Oficina",
    "Codigo_de_Oficina",
    "Oficina",
    "ID_Serie",
    "Serie",
    "ID_Linea",
    "Fila",
    "Modulo",
    "DNI_Ejecutivo",
    "Nombre_Ejecutivo",
    "Fecha_Reserva",
    "Hora_Reserva",
    "Prefijo_Fila",
    "Terminal_Reserva",
    "DNI_Cliente",
    "ID_Tipo_Cliente",
    "Tipo_Cliente",
    "Nombre_Cliente",
    "Email_Cliente",
    "Fecha_Creacion_Reserva",
    "Hora_Creacion_Reserva",
    "Fecha_Atencion",
    "Hora_Atencion",
    "Hora_Termino_Atencion",
    "Tiempo_Espera",
    "Tiempo_Atencion",
    "Cancelado",
    "Fecha_Cancelacion",
    "Usuario_que_Cancelo",
    "Motivo_de_Cancelacion",
    "Formulario",
    "Perdido",
    "Saltado",
    "Origen_de_Creacion",
    "Nombre_Agente",
    "Email_Agente",
    "DNI_Agente",
    "Modo_de_Atencion",
)

ATENCIONES_MOTIVO_FIELDS = (
    "fechaCierre",
    "ID_Ticket",
    "ID_Llamada",
    "ID_Oficina",
    "ID_Serie",
    "IDMotivoAtencion",
    "DescMotivoAtencion",
    "IDSubMotivoAtencion",
    "DescSubMotivoAtencion",
)

AGENDAMIENTOS_MOTIVO_FIELDS = (
    "fechaCierre",
    "ID_Reserva",
    "ID_Llamada",
    "ID_Oficina",
    "ID_Serie",
    "IDMotivoAtencion",
    "DescMotivoAtencion",
    "IDSubMotivoAtencion",
    "DescSubMotivoAtencion",
)

ATENCIONES_DATE_FIELDS = ("Fecha",)
ATENCIONES_INTEGER_FIELDS = (
    "ID_Oficina",
    "Codigo_de_Oficina",
    "ID_Serie",
    "ID_Linea",
    "Nro._Ticket",
    "ID_Tipo_Cliente",
)
ATENCIONES_TIME_FIELDS = (
    "Hora_Emision_Ticket",
    "Hora_Inicio_Atencion",
    "Hora_Termino_Atencion",
    "Tiempo_Espera",
    "Tiempo_Atencion",
)
AGENDAMIENTOS_DATE_FIELDS = (
    "Fecha_Reserva",
    "Fecha_Creacion_Reserva",
    "Fecha_Atencion",
    "Fecha_Cancelacion",
)
AGENDAMIENTOS_INTEGER_FIELDS = (
    "ID_Oficina",
    "Codigo_de_Oficina",
    "ID_Serie",
    "ID_Linea",
    "ID_Tipo_Cliente",
)
AGENDAMIENTOS_TIME_FIELDS = (
    "Hora_Reserva",
    "Hora_Creacion_Reserva",
    "Hora_Atencion",
    "Hora_Termino_Atencion",
    "Tiempo_Espera",
    "Tiempo_Atencion",
)

OUTPUT_SEPARATOR = "~|"
OUTPUT_ENCODING = "iso-8859-1"
