environment: prod
bucket: odi-portability-demo-prod
input_path: oci://odi-portability-demo-prod@REPLACE_NAMESPACE/input/customers.csv
output_path: oci://odi-portability-demo-prod@REPLACE_NAMESPACE/output/customers/
tax_rate: 0.18
minimum_records: 1
